use affector_val::SolAffectorValue;
pub(in crate::sol::svc::svce_calc) use aggr_mode::SolAggrMode;
pub(in crate::sol::svc::svce_calc) use context::SolContext;
pub(in crate::sol::svc::svce_calc) use custom::extend_with_custom_mods;
pub(in crate::sol::svc::svce_calc) use domain::SolDomain;
pub(in crate::sol::svc::svce_calc) use kind::SolModifierKind;
pub(in crate::sol::svc::svce_calc) use mod_ctx::SolCtxModifier;
pub(in crate::sol::svc::svce_calc) use mod_raw::SolRawModifier;
pub(in crate::sol::svc::svce_calc) use op::SolOp;
pub(in crate::sol::svc::svce_calc) use tgt_filter::SolAffecteeFilter;

mod affector_val;
mod aggr_mode;
mod context;
mod custom;
pub(in crate::sol::svc::svce_calc) mod debug;
mod domain;
mod kind;
mod mod_ctx;
mod mod_raw;
mod op;
mod tgt_filter;
