[package]
name = "refine-example-playground-core"
license = "Unlicense"
version = "0.1.0"
authors = ["DarkPhoenix <phoenix@mail.ru>"]
edition = "2024"
publish = false

[dependencies]
# Local
rc = { workspace = true }
redh = { workspace = true, features = ["phb-fs"] }
radc = { workspace = true, features = ["json-zfile"] }
# Non-local, workspace
itertools = { workspace = true }
time = { workspace = true, features = ["macros"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["time"] }
# Non-local, crate-specific
chrono = ">=0.4.45"
