[workspace]
members = [
    "refine-core",
    "refine-adc",
    "refine-edh",
    "refine-rs",
    "refine-http",
    "examples/playground",
]
resolver = "2"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[profile.release-opt]
inherits = "release"
codegen-units = 1
lto = "fat"
panic = "abort"
