[package]
name = "refine-http"
description = "HTTP interface built on top of refine-rs"
license = "AGPL-3.0-or-later"
version = "0.1.0"
authors = ["DarkPhoenix <phoenix@mail.ru>"]
edition = "2024"

[dependencies]
# Local
rs = { package = "refine-rs", path = "../refine-rs", features = ["serde"] }
radc = { package = "refine-adc", path = "../refine-adc", features = ["postcard-zfs"] }
redh = { package = "refine-edh", path = "../refine-edh", features = ["phb-http", "sde-http"] }
# Non-local
axum = { version = ">=0.8.9", default-features = false, features = ["http1", "json", "query", "tokio"] }
axum-extra = { version = ">=0.12.6", features = ["with-rejection"] }
config = { version = ">=0.15.25", features = ["toml"] }
http-body-util = ">=0.1.5"
serde = { version = ">=1.0.229", features = ["derive"] }
serde_json = { version = ">=1.0.151", features = ["float_roundtrip"] }  # Better float accuracy
thiserror = ">=2.0.20"
time = { version = ">=0.3.55", features = ["formatting", "macros"] }
tokio = { version = ">=1.53.1", features = ["macros", "net", "rt", "rt-multi-thread"] }
tower = { version = ">=0.5.3", features = ["util"] }
tower-http = { version = ">=0.7.0", features = ["normalize-path", "trace"] }
tower-request-id = ">=0.3.0"
tracing = ">=0.1.44"
tracing-appender = ">=0.2.5"
tracing-subscriber = { version = ">=0.3.23", features = ["time"] }
