pub use crate::sol::sole_item::{
    AddBoosterError, AddDroneError, AddFighterError, AddFwEffectError, AddImplantError, AddModuleError,
    AddModuleProjError, AddProjEffectError, AddProjEffectProjError, AddRigError, AddSetModuleChargeError,
    AddSkillError, AddSubsystemError, AddSwEffectError, ChangeModuleProjError, GetAutochargeInfoError,
    GetBoosterInfoError, GetChargeInfoError, GetDroneInfoError, GetFighterInfoError, GetFitBoosterInfosError,
    GetFitCharacterInfoError, GetFitDroneInfosError, GetFitFighterInfosError, GetFitFwEffectInfosError,
    GetFitImplantInfosError, GetFitModuleInfosError, GetFitRigInfosError, GetFitShipInfoError, GetFitSkillInfosError,
    GetFitStanceInfoError, GetFitSubsystemInfosError, GetFwEffectInfoError, GetImplantInfoError, GetItemInfoError,
    GetModuleInfoError, GetProjEffectInfoError, GetRigInfoError, GetSkillInfoError, GetSubsystemInfoError,
    GetSwEffectInfoError, RemoveBoosterError, RemoveCharacterError, RemoveChargeError, RemoveDroneError,
    RemoveFighterError, RemoveFitCharacterError, RemoveFitShipError, RemoveFitStanceError, RemoveFwEffectError,
    RemoveImplantError, RemoveItemError, RemoveModuleChargeError, RemoveModuleError, RemoveModuleProjError,
    RemoveProjEffectError, RemoveProjEffectProjError, RemoveRigError, RemoveShipError, RemoveSkillError,
    RemoveStanceError, RemoveSubsystemError, RemoveSwEffectError, SetBoosterSideEffectStateError, SetBoosterStateError,
    SetCharacterStateError, SetDroneStateError, SetFighterStateError, SetFitCharacterError, SetFitCharacterStateError,
    SetFitShipError, SetFitShipStateError, SetFitStanceError, SetFitStanceStateError, SetFwEffectStateError,
    SetImplantStateError, SetModuleStateError, SetProjEffectStateError, SetRigStateError, SetShipStateError,
    SetSkillLevelError, SetSkillStateError, SetStanceStateError, SetSubsystemStateError, SetSwEffectStateError,
};
