from .support import (
    make_eve_drone_armor,
    make_eve_drone_hull,
    make_eve_drone_shield,
    make_eve_local_aar,
    make_eve_local_ar,
    make_eve_local_asb,
    make_eve_local_hr,
    make_eve_local_sb,
    make_eve_remote_aar,
    make_eve_remote_ar,
    make_eve_remote_asb,
    make_eve_remote_hr,
    make_eve_remote_sar,
    make_eve_remote_sb,
    make_eve_tankable,
    setup_tank_basics,
)
