[package]
name = "refine-serde"
description = "Serialization helpers for refine-* entities"
license = "AGPL-3.0-or-later"
version = "0.1.0"
authors = ["DarkPhoenix <phoenix@mail.ru>"]
edition = "2024"

[dependencies]
# Local
refine-serde-derive = { path = "../refine-serde-derive" }
# Non-local
serde = { workspace = true }
serde_with = { workspace = true }
