[package]
name = "refine-example-playground-rs"
license = "Unlicense"
version = "0.1.0"
authors = ["DarkPhoenix <phoenix@mail.ru>"]
edition = "2024"
publish = false

[dependencies]
# Local
rs = { workspace = true }
radc = { workspace = true, features = ["postcard-zfile"] }
redh = { workspace = true, features = ["phb-fs"] }
# Non-local, workspace
time = { workspace = true, features = ["macros"] }
tokio = { workspace = true, features = ["rt", "macros"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["time"] }
