[package]
name = "refine-example-playground-rs"
version = "0.1.0"
authors = ["DarkPhoenix <phoenix@mail.ru>"]
edition = "2024"

[dependencies]
rs = { package = "refine-rs", path = "../../refine-rs", features = ["edh-phb-fs", "adc-fs"] }
time = { version = ">=0.3.53", features = ["macros"] }
tokio = { version = ">=1.53.0", features = ["macros", "rt"] }
tracing = ">=0.1.44"
tracing-subscriber = { version = ">=0.3.23", features = ["time"] }
