[package]
name = "refine-example-playground-rs"
license = "Unlicense"
version = "0.1.0"
authors = ["DarkPhoenix <phoenix@mail.ru>"]
edition = "2024"
publish = false

[dependencies]
# Local
rs = { package = "refine-rs", path = "../../refine-rs" }
radc = { package = "refine-adc", path = "../../refine-adc", features = ["postcard-zfs"] }
redh = { package = "refine-edh", path = "../../refine-edh", features = ["phb-fs"] }
# Non-local
time = { version = ">=0.3.55", features = ["macros"] }
tokio = { version = ">=1.53.1", features = ["rt", "macros"] }
tracing = ">=0.1.44"
tracing-subscriber = { version = ">=0.3.23", features = ["time"] }
