pub(in crate::info::valid) use activation_blocked::HValActivationBlockedFail;
pub(in crate::info::valid) use capital_module::HValCapitalModFail;
pub(in crate::info::valid) use charge_group::HValChargeGroupFail;
pub(in crate::info::valid) use charge_size::HValChargeSizeFail;
pub(in crate::info::valid) use charge_volume::HValChargeVolumeFail;
pub(in crate::info::valid) use drone_group::HValDroneGroupFail;
pub(in crate::info::valid) use fighter_squad_size::HValFighterSquadSizeFail;
pub(in crate::info::valid) use item_kind::HValItemKindFail;
pub(in crate::info::valid) use item_vs_ship_kind::HValItemVsShipKindFail;
pub(in crate::info::valid) use max_group::HValMaxGroupFail;
pub(in crate::info::valid) use max_type::HValMaxTypeFail;
pub(in crate::info::valid) use module_state::HValModuleStateFail;
pub(in crate::info::valid) use overload_skill::HValOverloadSkillFail;
pub(in crate::info::valid) use resource::HValResFail;
pub(in crate::info::valid) use rig_size::HValRigSizeFail;
pub(in crate::info::valid) use sec_zone::HValSecZoneFail;
pub(in crate::info::valid) use ship_limit::HValShipLimitFail;
pub(in crate::info::valid) use ship_stance::HValShipStanceFail;
pub(in crate::info::valid) use skill_reqs::HValSrqFail;
pub(in crate::info::valid) use slot_count::HValSlotCountFail;
pub(in crate::info::valid) use slot_index::HValSlotIndexFail;
pub(in crate::info::valid) use unusable_resource::HValUnusableResFail;
pub(in crate::info::valid) use unusable_slot::HValUnusableSlotFail;

mod activation_blocked;
mod capital_module;
mod charge_group;
mod charge_size;
mod charge_volume;
mod drone_group;
mod fighter_squad_size;
mod item_kind;
mod item_vs_ship_kind;
mod max_group;
mod max_type;
mod module_state;
mod overload_skill;
mod resource;
mod rig_size;
mod sec_zone;
mod ship_limit;
mod ship_stance;
mod skill_reqs;
mod slot_count;
mod slot_index;
mod unusable_resource;
mod unusable_slot;
