pub(in crate::info::valid) use capital_module::HValCapitalModFail;
pub(in crate::info::valid) use charge_group::HValChargeGroupFail;
pub(in crate::info::valid) use charge_size::HValChargeSizeFail;
pub(in crate::info::valid) use charge_volume::HValChargeVolumeFail;
pub(in crate::info::valid) use drone_group::HValDroneGroupFail;
pub(in crate::info::valid) use fighter_count::HValFighterCountFail;
pub(in crate::info::valid) use item_kind::HValItemKindFail;
pub(in crate::info::valid) use max_group::HValMaxGroupFail;
pub(in crate::info::valid) use module_state::HValModuleStateFail;
pub(in crate::info::valid) use resource::HValResFail;
pub(in crate::info::valid) use rig_size::HValRigSizeFail;
pub(in crate::info::valid) use ship_limit::HValShipLimitFail;
pub(in crate::info::valid) use skill_reqs::HValSrqFail;
pub(in crate::info::valid) use slot_count::HValSlotCountFail;
pub(in crate::info::valid) use slot_index::HValSlotIndexFail;

mod capital_module;
mod charge_group;
mod charge_size;
mod charge_volume;
mod drone_group;
mod fighter_count;
mod item_kind;
mod max_group;
mod module_state;
mod resource;
mod rig_size;
mod ship_limit;
mod skill_reqs;
mod slot_count;
mod slot_index;
