pub use sole_get_fit_rah_incoming_dmg::GetFitRahIncomingDmgError;
pub use sole_remove_fit_rah_incoming_dmg::RemoveFitRahIncomingDmgError;
pub use sole_set_default_incoming_dmg::SetDefaultIncomingDmgError;
pub use sole_set_fit_rah_incoming_dmg::SetFitRahIncomingDmgError;

mod sole_get_default_incoming_dmg;
mod sole_get_fit_rah_incoming_dmg;
mod sole_remove_fit_rah_incoming_dmg;
mod sole_set_default_incoming_dmg;
mod sole_set_fit_rah_incoming_dmg;
