pub use sole_add_drone::AddDroneError;
pub use sole_add_drone_mutation::AddDroneMutationError;
pub use sole_add_drone_proj::AddDroneProjError;
pub use sole_change_drone_mutation::ChangeDroneMutationError;
pub use sole_change_drone_proj::ChangeDroneProjError;
pub use sole_get_drone_info::GetDroneInfoError;
pub use sole_get_fit_drone_infos::GetFitDroneInfosError;
pub use sole_remove_drone::RemoveDroneError;
pub use sole_remove_drone_mutation::RemoveDroneMutationError;
pub use sole_remove_drone_proj::RemoveDroneProjError;
pub use sole_set_drone_state::SetDroneStateError;

mod sole_add_drone;
mod sole_add_drone_mutation;
mod sole_add_drone_proj;
mod sole_change_drone_mutation;
mod sole_change_drone_proj;
mod sole_get_drone_info;
mod sole_get_fit_drone_infos;
mod sole_remove_drone;
mod sole_remove_drone_mutation;
mod sole_remove_drone_proj;
mod sole_set_drone_state;
