pub(in crate::info::validation) use activation_blocked::HValActivationBlockedFail;
pub(in crate::info::validation) use capital_module::HValCapitalModFail;
pub(in crate::info::validation) use charge_group::HValChargeGroupFail;
pub(in crate::info::validation) use charge_parent_group::HValChargeParentGroupFail;
pub(in crate::info::validation) use charge_size::HValChargeSizeFail;
pub(in crate::info::validation) use charge_volume::HValChargeVolumeFail;
pub(in crate::info::validation) use drone_group::HValDroneGroupFail;
pub(in crate::info::validation) use effect_stopper::HValEffectStopperFail;
pub(in crate::info::validation) use fighter_squad_size::HValFighterSquadSizeFail;
pub(in crate::info::validation) use item_kind::HValItemKindFail;
pub(in crate::info::validation) use item_vs_ship_kind::HValItemVsShipKindFail;
pub(in crate::info::validation) use max_group::HValMaxGroupFail;
pub(in crate::info::validation) use max_type::HValMaxTypeFail;
pub(in crate::info::validation) use module_state::HValModuleStateFail;
pub(in crate::info::validation) use not_loaded_item::HValNotLoadedItemFail;
pub(in crate::info::validation) use overload_skill::HValOverloadSkillFail;
pub(in crate::info::validation) use proj_immunity::HValProjImmunityFail;
pub(in crate::info::validation) use projectee_filter::HValProjFilterFail;
pub(in crate::info::validation) use resource::HValResFail;
pub(in crate::info::validation) use rig_size::HValRigSizeFail;
pub(in crate::info::validation) use sec_zone::HValSecZoneFail;
pub(in crate::info::validation) use ship_limit::HValShipLimitFail;
pub(in crate::info::validation) use ship_stance::HValShipStanceFail;
pub(in crate::info::validation) use skill_reqs::HValSrqFail;
pub(in crate::info::validation) use slot_count::HValSlotCountFail;
pub(in crate::info::validation) use slot_index::HValSlotIndexFail;
pub(in crate::info::validation) use unusable_resource::HValUnusableResFail;
pub(in crate::info::validation) use unusable_slot::HValUnusableSlotFail;

mod activation_blocked;
mod capital_module;
mod charge_group;
mod charge_parent_group;
mod charge_size;
mod charge_volume;
mod drone_group;
mod effect_stopper;
mod fighter_squad_size;
mod item_kind;
mod item_vs_ship_kind;
mod max_group;
mod max_type;
mod module_state;
mod not_loaded_item;
mod overload_skill;
mod proj_immunity;
mod projectee_filter;
mod resource;
mod rig_size;
mod sec_zone;
mod ship_limit;
mod ship_stance;
mod skill_reqs;
mod slot_count;
mod slot_index;
mod unusable_resource;
mod unusable_slot;
