from tests import approx, check_no_field
from tests.features.reactive_armor_hardener import setup_rah


def test_random(client, consts):
    eve_rah_info = setup_rah(client=client, consts=consts)
    client.create_sources()
    api_sol = client.create_sol(default_incoming_dmg=(1, 1, 0, 0))
    api_fit = api_sol.create_fit(rah_incoming_dmg=(0, 0, 0, 1))
    api_ship = api_fit.set_ship(type_id=eve_rah_info.ship_id)
    api_rah = api_fit.add_mod(type_id=eve_rah_info.rah_id, state=consts.ApiState.active)
    # Verification
    api_ship.update()
    assert api_ship.attrs[eve_rah_info.res_em_attr_id].dogma == approx(0.5)
    assert api_ship.attrs[eve_rah_info.res_therm_attr_id].dogma == approx(0.65)
    assert api_ship.attrs[eve_rah_info.res_kin_attr_id].dogma == approx(0.75)
    assert api_ship.attrs[eve_rah_info.res_expl_attr_id].dogma == approx(0.36)
    api_rah.update()
    assert api_rah.attrs[eve_rah_info.res_em_attr_id].dogma == approx(1.0)
    assert api_rah.attrs[eve_rah_info.res_therm_attr_id].dogma == approx(1.0)
    assert api_rah.attrs[eve_rah_info.res_kin_attr_id].dogma == approx(1.0)
    assert api_rah.attrs[eve_rah_info.res_expl_attr_id].dogma == approx(0.4)
    api_fit.set_rah_incoming_dmg(dmg_profile=None)
    api_sol.update()
    api_ship.update()
    assert api_ship.attrs[eve_rah_info.res_em_attr_id].dogma == approx(0.35)
    assert api_ship.attrs[eve_rah_info.res_therm_attr_id].dogma == approx(0.455)
    assert api_ship.attrs[eve_rah_info.res_kin_attr_id].dogma == approx(0.75)
    assert api_ship.attrs[eve_rah_info.res_expl_attr_id].dogma == approx(0.9)
    api_rah.update()
    assert api_rah.attrs[eve_rah_info.res_em_attr_id].dogma == approx(0.7)
    assert api_rah.attrs[eve_rah_info.res_therm_attr_id].dogma == approx(0.7)
    assert api_rah.attrs[eve_rah_info.res_kin_attr_id].dogma == approx(1)
    assert api_rah.attrs[eve_rah_info.res_expl_attr_id].dogma == approx(1)
    api_fit.set_rah_incoming_dmg(dmg_profile=(1, 1, 1, 1))
    api_ship.update()
    assert api_ship.attrs[eve_rah_info.res_em_attr_id].dogma == approx(0.5)
    assert api_ship.attrs[eve_rah_info.res_therm_attr_id].dogma == approx(0.60125)
    assert api_ship.attrs[eve_rah_info.res_kin_attr_id].dogma == approx(0.615)
    assert api_ship.attrs[eve_rah_info.res_expl_attr_id].dogma == approx(0.5895)
    api_rah.update()
    assert api_rah.attrs[eve_rah_info.res_em_attr_id].dogma == approx(1.0)
    assert api_rah.attrs[eve_rah_info.res_therm_attr_id].dogma == approx(0.925)
    assert api_rah.attrs[eve_rah_info.res_kin_attr_id].dogma == approx(0.82)
    assert api_rah.attrs[eve_rah_info.res_expl_attr_id].dogma == approx(0.655)
