[package]
name = "refine-rs"
description = "Higher-level Rust interface built on top of refine-core"
license = "AGPL-3.0-or-later"
version = "0.1.0"
authors = ["DarkPhoenix <phoenix@mail.ru>"]
edition = "2024"

[dependencies]
# Local
rc = { workspace = true }
redh = { workspace = true, optional = true }
radc = { workspace = true, optional = true }
# Non-local
derive_more = { workspace = true, features = ["display"] }
fixedstr = { workspace = true, features = ["fstr"] }
parking_lot = { workspace = true, features = ["nightly"] }
serde = { workspace = true, features = ["derive"], optional = true }
serde_tuple = { workspace = true, optional = true }
serde_with = { workspace = true, optional = true }
thiserror = { workspace = true }
time = { workspace = true }
tokio = { workspace = true, features = ["sync", "time"] }
tokio-rayon = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true, features = ["fast-rng", "v4"] }

[features]
serde = [
    "dep:serde",
    "dep:serde_tuple",
    "dep:serde_with",
    "rc/serde",
    "fixedstr/serde",
    "time/formatting",
    "time/macros",
    "uuid/serde",
]
edh-phb-fs = [
    "dep:redh",
    "redh/phb-fs",
]
edh-phb-http = [
    "dep:redh",
    "redh/phb-http",
]
adc-fs = [
    "dep:radc",
    "radc/postcard-zfile",
]
