[package]
name = "refine-rs"
description = "Higher-level Rust interface built on top of refine-core"
license = "AGPL-3.0-or-later"
version = "0.1.0"
authors = ["DarkPhoenix <phoenix@mail.ru>"]
edition = "2024"

[dependencies]
rc = { package = "refine-core", path = "../refine-core" }
redh = { package = "refine-edh", path = "../refine-edh", optional = true }
radc = { package = "refine-adc", path = "../refine-adc", optional = true }
derive_more = { version = ">=2.1.1", features = ["display"] }
parking_lot = { version = ">=0.12.5", features = ["nightly"] }
serde = { version = ">=1.0.228", features = ["derive"], optional = true }
serde_json = { version = ">=1.0.150", optional = true }
serde_tuple = { version = ">=1.1.3", optional = true }
serde_with = { version = ">=3.21.0", optional = true }
thiserror = ">=2.0.18"
tokio = { version = ">=1.53.0", features = ["full"] }
tokio-rayon = ">=2.1.0"
tracing = ">=0.1.44"
uuid = { version = ">=1.24.0", features = ["v4", "fast-rng"] }

[features]
serde = [
    "dep:serde",
    "dep:serde_json",
    "dep:serde_tuple",
    "dep:serde_with",
]
edh-phb-fs = [
    "dep:redh",
    "redh/phb-fs",
]
edh-phb-http = [
    "dep:redh",
    "redh/phb-http",
]
adc-fs = [
    "dep:radc",
    "radc/json-zfile",
]
