[package]
name = "refine-rs"
version = "0.1.0"
authors = ["DarkPhoenix <phoenix@mail.ru>"]
edition = "2024"

[dependencies]
rc = { package = "refine-core", path = "../refine-core" }
redh = { package = "refine-edh", path = "../refine-edh", features = ["phb-http"] }
radc = { package = "refine-adc", path = "../refine-adc", features = ["json-zfile"] }
