[package]
name = "refine-edh"
description = "EVE data handlers for refine-core crate"
license = "AGPL-3.0-or-later"
version = "0.1.0"
authors = ["DarkPhoenix <phoenix@mail.ru>"]
edition = "2024"

[dependencies]
# Local
rc = { workspace = true }
# Non-local
reqwest = { workspace = true, features = ["blocking"], optional = true }
serde = { workspace = true, features = ["derive"], optional = true }
serde_json = { workspace = true, features = ["raw_value"], optional = true }
serde_with = { workspace = true, optional = true }
thiserror = { workspace = true }
url = { workspace = true, optional = true }

[features]
phb-http = ["dep:serde", "dep:serde_json", "dep:serde_with", "dep:reqwest", "dep:url"]
phb-fs = ["dep:serde", "dep:serde_json", "dep:serde_with"]
