pub mod basic;
pub use crate::{
    sol::{
        misc::{NewBreacherInfoError, NewDpsProfileError},
        sole_calc::{
            GetItemAttrError, IterItemAttrsError, IterItemEffectsError, IterItemModifiersError, SetItemEffectModeError,
            SetItemEffectModesError,
        },
        sole_dps_profile::{GetFitRahIncomingDpsError, RemoveFitRahIncomingDpsError, SetFitRahIncomingDpsError},
        sole_fit::{GetFitInfoError, RemoveFitError, SetFitFleetError, UnsetFitFleetError},
        sole_fleet::{GetFleetInfoError, RemoveFleetError},
        sole_item::{
            AddBoosterError, AddDroneError, AddDroneMutationError, AddDroneProjError, AddFighterError,
            AddFighterProjError, AddFwEffectError, AddImplantError, AddModuleError, AddModuleMutationError,
            AddModuleProjError, AddProjEffectProjError, AddRigError, AddServiceError, AddSkillError, AddSubsystemError,
            ChangeDroneMutationError, ChangeDroneProjError, ChangeFighterProjError, ChangeModuleMutationError,
            ChangeModuleProjError, GetAutochargeInfoError, GetBoosterInfoError, GetChargeInfoError, GetDroneInfoError,
            GetFighterInfoError, GetFitBoosterInfosError, GetFitCharacterInfoError, GetFitDroneInfosError,
            GetFitFighterInfosError, GetFitFwEffectInfosError, GetFitImplantInfosError, GetFitModuleInfosError,
            GetFitRigsError, GetFitServiceInfosError, GetFitShipInfoError, GetFitSkillsError, GetFitStanceInfoError,
            GetFitSubsystemsError, GetFwEffectInfoError, GetImplantInfoError, GetItemInfoError, GetModuleInfoError,
            GetProjEffectInfoError, GetRigInfoError, GetServiceInfoError, GetSkillInfoError, GetSubsystemInfoError,
            GetSwEffectInfoError, RemoveBoosterError, RemoveCharacterError, RemoveChargeError, RemoveDroneError,
            RemoveDroneMutationError, RemoveDroneProjError, RemoveFighterCountOverrideError, RemoveFighterError,
            RemoveFighterProjError, RemoveFitCharacterError, RemoveFitShipError, RemoveFitStanceError,
            RemoveFwEffectError, RemoveImplantError, RemoveItemError, RemoveModuleChargeError, RemoveModuleError,
            RemoveModuleMutationError, RemoveModuleProjError, RemoveProjEffectError, RemoveProjEffectProjError,
            RemoveRigError, RemoveServiceError, RemoveShipError, RemoveSkillError, RemoveStanceError,
            RemoveSubsystemError, RemoveSwEffectError, SetAutochargeStateError, SetBoosterSideEffectStateError,
            SetBoosterStateError, SetCharacterStateError, SetChargeStateError, SetDroneStateError,
            SetFighterCountOverrideError, SetFighterStateError, SetFitCharacterError, SetFitCharacterStateError,
            SetFitShipError, SetFitShipStateError, SetFitStanceError, SetFitStanceStateError, SetFwEffectStateError,
            SetImplantStateError, SetModuleChargeError, SetModuleStateError, SetProjEffectStateError, SetRigStateError,
            SetServiceStateError, SetShipStateError, SetSkillLevelError, SetSkillStateError, SetStanceStateError,
            SetSubsystemStateError, SetSwEffectStateError,
        },
        sole_sec::{GetFitSecStatusError, SetFitSecStatusError},
        sole_vast::{TryFitItemsError, ValidateFitError},
    },
    src::SrcInitError,
};
