mod vaste_effects_started_stopped;
mod vaste_fit_added_removed;
mod vaste_item_added_removed;
mod vaste_item_loaded_unloaded;
mod vaste_item_state_activated_deactivated;
mod vaste_item_state_activated_deactivated_loaded;
mod vaste_misc;
