use crate::{
    Count, PValue, TriStateField, UnitInterval, Value,
    stats::{
        StatCapSim, StatDmg, StatEhp, StatErps, StatHp, StatInJam, StatJump, StatMining, StatOutReps, StatResists,
        StatResource, StatRps, StatSensors, StatSlot,
    },
};

pub struct FitStats {
    // Fit output stats
    pub dmg: Option<Vec<Option<StatDmg>>> = None,
    pub mps: Option<Vec<StatMining>> = None,
    pub outgoing_nps: Option<Vec<Option<PValue>>> = None,
    pub outgoing_rps: Option<Vec<Option<StatOutReps>>> = None,
    pub outgoing_cps: Option<Vec<Option<PValue>>> = None,
    // Fit resources
    pub cpu: Option<Vec<StatResource>> = None,
    pub powergrid: Option<Vec<StatResource>> = None,
    pub calibration: Option<Vec<StatResource>> = None,
    pub drone_bay_volume: Option<Vec<StatResource>> = None,
    pub drone_bandwidth: Option<Vec<StatResource>> = None,
    pub fighter_bay_volume: Option<Vec<StatResource>> = None,
    // Fit slots
    pub high_slots: Option<Vec<StatSlot>> = None,
    pub mid_slots: Option<Vec<StatSlot>> = None,
    pub low_slots: Option<Vec<StatSlot>> = None,
    pub turret_slots: Option<Vec<StatSlot>> = None,
    pub launcher_slots: Option<Vec<StatSlot>> = None,
    pub rig_slots: Option<Vec<StatSlot>> = None,
    pub service_slots: Option<Vec<StatSlot>> = None,
    pub subsystem_slots: Option<Vec<StatSlot>> = None,
    pub launched_drones: Option<Vec<StatSlot>> = None,
    pub launched_fighters: Option<Vec<StatSlot>> = None,
    pub launched_light_fighters: Option<Vec<StatSlot>> = None,
    pub launched_heavy_fighters: Option<Vec<StatSlot>> = None,
    pub launched_support_fighters: Option<Vec<StatSlot>> = None,
    pub launched_st_light_fighters: Option<Vec<StatSlot>> = None,
    pub launched_st_heavy_fighters: Option<Vec<StatSlot>> = None,
    pub launched_st_support_fighters: Option<Vec<StatSlot>> = None,
    // Ship tank
    pub resists: TriStateField<Vec<StatResists>> = TriStateField::Absent,
    pub hp: TriStateField<Vec<StatHp>> = TriStateField::Absent,
    pub ehp: TriStateField<Vec<StatEhp>> = TriStateField::Absent,
    pub wc_ehp: TriStateField<Vec<StatEhp>> = TriStateField::Absent,
    pub rps: TriStateField<Vec<StatRps>> = TriStateField::Absent,
    pub erps: TriStateField<Vec<StatErps>> = TriStateField::Absent,
    pub breach_resist: TriStateField<Vec<UnitInterval>> = TriStateField::Absent,
    // Ship cap
    pub cap_amount: TriStateField<Vec<PValue>> = TriStateField::Absent,
    pub cap_balance: TriStateField<Vec<Option<Value>>> = TriStateField::Absent,
    pub cap_sim: TriStateField<Vec<Option<StatCapSim>>> = TriStateField::Absent,
    pub neut_resist: TriStateField<Vec<UnitInterval>> = TriStateField::Absent,
    // Ship sensors
    pub locks: TriStateField<Vec<Count>> = TriStateField::Absent,
    pub lock_range: TriStateField<Vec<PValue>> = TriStateField::Absent,
    pub scan_res: TriStateField<Vec<PValue>> = TriStateField::Absent,
    pub sensors: TriStateField<Vec<StatSensors>> = TriStateField::Absent,
    pub dscan_range: TriStateField<Vec<PValue>> = TriStateField::Absent,
    pub probing_size: TriStateField<Vec<PValue>> = TriStateField::Absent,
    pub incoming_jam: TriStateField<Vec<StatInJam>> = TriStateField::Absent,
    // Ship mobility
    pub speed: TriStateField<Vec<PValue>> = TriStateField::Absent,
    pub agility: TriStateField<Vec<PValue>> = TriStateField::Absent,
    pub align_time: TriStateField<Vec<PValue>> = TriStateField::Absent,
    pub sig_radius: TriStateField<Vec<PValue>> = TriStateField::Absent,
    pub mass: TriStateField<Vec<PValue>> = TriStateField::Absent,
    pub warp_speed: TriStateField<Vec<PValue>> = TriStateField::Absent,
    pub max_warp_range: TriStateField<Vec<PValue>> = TriStateField::Absent,
    pub jump: TriStateField<Vec<StatJump>> = TriStateField::Absent,
}
