[package]
name = "refine-adc"
description = "Adapted data cachers for refine-core crate"
license = "AGPL-3.0-or-later"
version = "0.1.0"
authors = ["DarkPhoenix <phoenix@mail.ru>"]
edition = "2024"

[dependencies]
# Local
rc = { workspace = true }
# Non-local
postcard = { workspace = true, features = ["use-std"], optional = true }
serde = { workspace = true, features = ["derive"], optional = true }
serde_json = { workspace = true, optional = true }
thiserror = { workspace = true, optional = true }
zstd = { workspace = true, optional = true }

[features]
json-zfile = [
    "dep:serde",
    "dep:serde_json",
    "dep:thiserror",
    "dep:zstd",
    "rc/serde-ad",
]
postcard-zfile = [
    "dep:postcard",
    "dep:serde",
    "dep:thiserror",
    "dep:zstd",
    "rc/serde-ad",
]
