pub use add_mutation::AddDroneMutationError;
pub use add_proj::AddDroneProjError;
pub use change_mutation::ChangeDroneMutationError;
pub use change_proj::ChangeDroneProjError;
pub use drone::{Drone, DroneMut};
pub use get::GetDroneError;
pub use remove_mutation::RemoveDroneMutationError;
pub use remove_proj::RemoveDroneProjError;

mod add;
mod add_mutation;
mod add_proj;
mod change_mutation;
mod change_proj;
mod drone;
mod fit_iter;
mod get;
mod remove;
mod remove_mutation;
mod remove_proj;
mod set_state;
