use crate::{
    ad::{AAttrId, ACustomAttrId},
    ed::EAttrId,
};

impl AAttrId {
    // Composite constants
    pub(crate) const BUFF_MERGE_ATTRS: [(Self, Self); 4] = [
        (Self::WARFARE_BUFF1_ID, Self::WARFARE_BUFF1_VAL),
        (Self::WARFARE_BUFF2_ID, Self::WARFARE_BUFF2_VAL),
        (Self::WARFARE_BUFF3_ID, Self::WARFARE_BUFF3_VAL),
        (Self::WARFARE_BUFF4_ID, Self::WARFARE_BUFF4_VAL),
    ];
    pub(crate) const LIMITED_PRECISION_ATTRS: [Self; 4] =
        [Self::CPU, Self::POWER, Self::CPU_OUTPUT, Self::POWER_OUTPUT];
    // Attribute IDs
    pub(crate) const MASS: Self = Self::from_eid(EAttrId::MASS);
    pub(crate) const CAPACITOR_NEED: Self = Self::from_eid(EAttrId::CAPACITOR_NEED);
    pub(crate) const HP: Self = Self::from_eid(EAttrId::HP);
    pub(crate) const POWER_OUTPUT: Self = Self::from_eid(EAttrId::POWER_OUTPUT);
    pub(crate) const LOW_SLOTS: Self = Self::from_eid(EAttrId::LOW_SLOTS);
    pub(crate) const MED_SLOTS: Self = Self::from_eid(EAttrId::MED_SLOTS);
    pub(crate) const HI_SLOTS: Self = Self::from_eid(EAttrId::HI_SLOTS);
    pub(crate) const SPEED_FACTOR: Self = Self::from_eid(EAttrId::SPEED_FACTOR);
    pub(crate) const POWER: Self = Self::from_eid(EAttrId::POWER);
    pub(crate) const MAX_VELOCITY: Self = Self::from_eid(EAttrId::MAX_VELOCITY);
    pub(crate) const CAPACITY: Self = Self::from_eid(EAttrId::CAPACITY);
    pub(crate) const CPU_OUTPUT: Self = Self::from_eid(EAttrId::CPU_OUTPUT);
    pub(crate) const CPU: Self = Self::from_eid(EAttrId::CPU);
    pub(crate) const SPEED: Self = Self::from_eid(EAttrId::SPEED);
    pub(crate) const MAX_RANGE: Self = Self::from_eid(EAttrId::MAX_RANGE);
    pub(crate) const RECHARGE_RATE: Self = Self::from_eid(EAttrId::RECHARGE_RATE);
    pub(crate) const CHARGE_RATE: Self = Self::from_eid(EAttrId::CHARGE_RATE);
    pub(crate) const DMG_MULT: Self = Self::from_eid(EAttrId::DMG_MULT);
    pub(crate) const CAPACITOR_BONUS: Self = Self::from_eid(EAttrId::CAPACITOR_BONUS);
    pub(crate) const SHIELD_BONUS: Self = Self::from_eid(EAttrId::SHIELD_BONUS);
    pub(crate) const AGILITY: Self = Self::from_eid(EAttrId::AGILITY);
    pub(crate) const MAX_TARGET_RANGE: Self = Self::from_eid(EAttrId::MAX_TARGET_RANGE);
    pub(crate) const MINING_AMOUNT: Self = Self::from_eid(EAttrId::MINING_AMOUNT);
    pub(crate) const STRUCT_DMG_AMOUNT: Self = Self::from_eid(EAttrId::STRUCT_DMG_AMOUNT);
    pub(crate) const ARMOR_DMG_AMOUNT: Self = Self::from_eid(EAttrId::ARMOR_DMG_AMOUNT);
    pub(crate) const POWER_TRANSFER_AMOUNT: Self = Self::from_eid(EAttrId::POWER_TRANSFER_AMOUNT);
    pub(crate) const ENERGY_NEUT_AMOUNT: Self = Self::from_eid(EAttrId::ENERGY_NEUT_AMOUNT);
    pub(crate) const EMP_FIELD_RANGE: Self = Self::from_eid(EAttrId::EMP_FIELD_RANGE);
    pub(crate) const LAUNCHER_SLOTS_LEFT: Self = Self::from_eid(EAttrId::LAUNCHER_SLOTS_LEFT);
    pub(crate) const TURRET_SLOTS_LEFT: Self = Self::from_eid(EAttrId::TURRET_SLOTS_LEFT);
    pub(crate) const WARP_SCRAMBLE_RANGE: Self = Self::from_eid(EAttrId::WARP_SCRAMBLE_RANGE);
    pub(crate) const WARP_SCRAMBLE_STATUS: Self = Self::from_eid(EAttrId::WARP_SCRAMBLE_STATUS);
    pub(crate) const WARP_SCRAMBLE_STRENGTH: Self = Self::from_eid(EAttrId::WARP_SCRAMBLE_STRENGTH);
    pub(crate) const KIN_DMG_RESONANCE: Self = Self::from_eid(EAttrId::KIN_DMG_RESONANCE);
    pub(crate) const THERM_DMG_RESONANCE: Self = Self::from_eid(EAttrId::THERM_DMG_RESONANCE);
    pub(crate) const EXPL_DMG_RESONANCE: Self = Self::from_eid(EAttrId::EXPL_DMG_RESONANCE);
    pub(crate) const EM_DMG_RESONANCE: Self = Self::from_eid(EAttrId::EM_DMG_RESONANCE);
    pub(crate) const EM_DMG: Self = Self::from_eid(EAttrId::EM_DMG);
    pub(crate) const EXPL_DMG: Self = Self::from_eid(EAttrId::EXPL_DMG);
    pub(crate) const KIN_DMG: Self = Self::from_eid(EAttrId::KIN_DMG);
    pub(crate) const THERM_DMG: Self = Self::from_eid(EAttrId::THERM_DMG);
    pub(crate) const AMMO_LOADED: Self = Self::from_eid(EAttrId::AMMO_LOADED);
    pub(crate) const CHARGE_SIZE: Self = Self::from_eid(EAttrId::CHARGE_SIZE);
    pub(crate) const LAUNCHER_GROUP: Self = Self::from_eid(EAttrId::LAUNCHER_GROUP);
    pub(crate) const WARP_CAPACITOR_NEED: Self = Self::from_eid(EAttrId::WARP_CAPACITOR_NEED);
    pub(crate) const FALLOFF: Self = Self::from_eid(EAttrId::FALLOFF);
    pub(crate) const TRACKING_SPEED: Self = Self::from_eid(EAttrId::TRACKING_SPEED);
    pub(crate) const VOLUME: Self = Self::from_eid(EAttrId::VOLUME);
    pub(crate) const RADIUS: Self = Self::from_eid(EAttrId::RADIUS);
    pub(crate) const TGT_FILTER_TYPELIST_ID: Self = Self::from_eid(EAttrId::TGT_FILTER_TYPELIST_ID);
    pub(crate) const MAX_LOCKED_TARGETS: Self = Self::from_eid(EAttrId::MAX_LOCKED_TARGETS);
    pub(crate) const SCAN_RADAR_STRENGTH: Self = Self::from_eid(EAttrId::SCAN_RADAR_STRENGTH);
    pub(crate) const SCAN_LADAR_STRENGTH: Self = Self::from_eid(EAttrId::SCAN_LADAR_STRENGTH);
    pub(crate) const SCAN_MAGNETOMETRIC_STRENGTH: Self = Self::from_eid(EAttrId::SCAN_MAGNETOMETRIC_STRENGTH);
    pub(crate) const SCAN_GRAVIMETRIC_STRENGTH: Self = Self::from_eid(EAttrId::SCAN_GRAVIMETRIC_STRENGTH);
    pub(crate) const MISSILE_DMG_MULT: Self = Self::from_eid(EAttrId::MISSILE_DMG_MULT);
    pub(crate) const SCAN_GRAVIMETRIC_STRENGTH_BONUS: Self = Self::from_eid(EAttrId::SCAN_GRAVIMETRIC_STRENGTH_BONUS);
    pub(crate) const SCAN_LADAR_STRENGTH_BONUS: Self = Self::from_eid(EAttrId::SCAN_LADAR_STRENGTH_BONUS);
    pub(crate) const SCAN_MAGNETOMETRIC_STRENGTH_BONUS: Self =
        Self::from_eid(EAttrId::SCAN_MAGNETOMETRIC_STRENGTH_BONUS);
    pub(crate) const SCAN_RADAR_STRENGTH_BONUS: Self = Self::from_eid(EAttrId::SCAN_RADAR_STRENGTH_BONUS);
    pub(crate) const SHIELD_CAPACITY: Self = Self::from_eid(EAttrId::SHIELD_CAPACITY);
    pub(crate) const ARMOR_HP: Self = Self::from_eid(EAttrId::ARMOR_HP);
    pub(crate) const ARMOR_EM_DMG_RESONANCE: Self = Self::from_eid(EAttrId::ARMOR_EM_DMG_RESONANCE);
    pub(crate) const ARMOR_EXPL_DMG_RESONANCE: Self = Self::from_eid(EAttrId::ARMOR_EXPL_DMG_RESONANCE);
    pub(crate) const ARMOR_KIN_DMG_RESONANCE: Self = Self::from_eid(EAttrId::ARMOR_KIN_DMG_RESONANCE);
    pub(crate) const ARMOR_THERM_DMG_RESONANCE: Self = Self::from_eid(EAttrId::ARMOR_THERM_DMG_RESONANCE);
    pub(crate) const SHIELD_EM_DMG_RESONANCE: Self = Self::from_eid(EAttrId::SHIELD_EM_DMG_RESONANCE);
    pub(crate) const SHIELD_EXPL_DMG_RESONANCE: Self = Self::from_eid(EAttrId::SHIELD_EXPL_DMG_RESONANCE);
    pub(crate) const SHIELD_KIN_DMG_RESONANCE: Self = Self::from_eid(EAttrId::SHIELD_KIN_DMG_RESONANCE);
    pub(crate) const SHIELD_THERM_DMG_RESONANCE: Self = Self::from_eid(EAttrId::SHIELD_THERM_DMG_RESONANCE);
    pub(crate) const SKILL_LEVEL: Self = Self::from_eid(EAttrId::SKILL_LEVEL);
    pub(crate) const EXPLOSION_DELAY: Self = Self::from_eid(EAttrId::EXPLOSION_DELAY);
    pub(crate) const DRONE_CAPACITY: Self = Self::from_eid(EAttrId::DRONE_CAPACITY);
    pub(crate) const DMG_MULT_BONUS: Self = Self::from_eid(EAttrId::DMG_MULT_BONUS);
    pub(crate) const ROF_BONUS: Self = Self::from_eid(EAttrId::ROF_BONUS);
    pub(crate) const MAX_TARGET_RANGE_BONUS: Self = Self::from_eid(EAttrId::MAX_TARGET_RANGE_BONUS);
    pub(crate) const IMPLANTNESS: Self = Self::from_eid(EAttrId::IMPLANTNESS);
    pub(crate) const FALLOFF_BONUS: Self = Self::from_eid(EAttrId::FALLOFF_BONUS);
    pub(crate) const MAX_RANGE_BONUS: Self = Self::from_eid(EAttrId::MAX_RANGE_BONUS);
    pub(crate) const MAX_ACTIVE_DRONES: Self = Self::from_eid(EAttrId::MAX_ACTIVE_DRONES);
    pub(crate) const DRONE_CONTROL_DISTANCE: Self = Self::from_eid(EAttrId::DRONE_CONTROL_DISTANCE);
    pub(crate) const SHIELD_RECHARGE_RATE: Self = Self::from_eid(EAttrId::SHIELD_RECHARGE_RATE);
    pub(crate) const CAPACITOR_CAPACITY: Self = Self::from_eid(EAttrId::CAPACITOR_CAPACITY);
    pub(crate) const ENTITY_CRUISE_SPEED: Self = Self::from_eid(EAttrId::ENTITY_CRUISE_SPEED);
    pub(crate) const MISSILE_VELOCITY_BONUS: Self = Self::from_eid(EAttrId::MISSILE_VELOCITY_BONUS);
    pub(crate) const SIG_RADIUS: Self = Self::from_eid(EAttrId::SIG_RADIUS);
    pub(crate) const SIG_RADIUS_BONUS: Self = Self::from_eid(EAttrId::SIG_RADIUS_BONUS);
    pub(crate) const CLOAKING_TARGETING_DELAY: Self = Self::from_eid(EAttrId::CLOAKING_TARGETING_DELAY);
    pub(crate) const SCAN_RESOLUTION: Self = Self::from_eid(EAttrId::SCAN_RESOLUTION);
    pub(crate) const SCAN_RESOLUTION_BONUS: Self = Self::from_eid(EAttrId::SCAN_RESOLUTION_BONUS);
    pub(crate) const SPEED_BOOST_FACTOR: Self = Self::from_eid(EAttrId::SPEED_BOOST_FACTOR);
    pub(crate) const EXPLOSION_DELAY_BONUS: Self = Self::from_eid(EAttrId::EXPLOSION_DELAY_BONUS);
    pub(crate) const WARP_SPEED_MULT: Self = Self::from_eid(EAttrId::WARP_SPEED_MULT);
    pub(crate) const LAUNCHER_GROUP2: Self = Self::from_eid(EAttrId::LAUNCHER_GROUP2);
    pub(crate) const LAUNCHER_GROUP3: Self = Self::from_eid(EAttrId::LAUNCHER_GROUP3);
    pub(crate) const CHARGE_GROUP1: Self = Self::from_eid(EAttrId::CHARGE_GROUP1);
    pub(crate) const CHARGE_GROUP2: Self = Self::from_eid(EAttrId::CHARGE_GROUP2);
    pub(crate) const CHARGE_GROUP3: Self = Self::from_eid(EAttrId::CHARGE_GROUP3);
    pub(crate) const CHARGE_GROUP4: Self = Self::from_eid(EAttrId::CHARGE_GROUP4);
    pub(crate) const CHARGE_GROUP5: Self = Self::from_eid(EAttrId::CHARGE_GROUP5);
    pub(crate) const CLOAKING_TARGETING_DELAY_BONUS: Self = Self::from_eid(EAttrId::CLOAKING_TARGETING_DELAY_BONUS);
    pub(crate) const OPTIMAL_SIG_RADIUS: Self = Self::from_eid(EAttrId::OPTIMAL_SIG_RADIUS);
    pub(crate) const MISSILE_ENTITY_VELOCITY_MULTIPLIER: Self =
        Self::from_eid(EAttrId::MISSILE_ENTITY_VELOCITY_MULTIPLIER);
    pub(crate) const MISSILE_ENTITY_FLIGHT_TIME_MULTIPLIER: Self =
        Self::from_eid(EAttrId::MISSILE_ENTITY_FLIGHT_TIME_MULTIPLIER);
    pub(crate) const AOE_VELOCITY: Self = Self::from_eid(EAttrId::AOE_VELOCITY);
    pub(crate) const AOE_CLOUD_SIZE: Self = Self::from_eid(EAttrId::AOE_CLOUD_SIZE);
    pub(crate) const MOD_REACTIVATION_DELAY: Self = Self::from_eid(EAttrId::MOD_REACTIVATION_DELAY);
    pub(crate) const MAX_GROUP_ACTIVE: Self = Self::from_eid(EAttrId::MAX_GROUP_ACTIVE);
    pub(crate) const TRACKING_SPEED_BONUS: Self = Self::from_eid(EAttrId::TRACKING_SPEED_BONUS);
    pub(crate) const CRYSTAL_VOLATILITY_CHANCE: Self = Self::from_eid(EAttrId::CRYSTAL_VOLATILITY_CHANCE);
    pub(crate) const CRYSTAL_VOLATILITY_DMG: Self = Self::from_eid(EAttrId::CRYSTAL_VOLATILITY_DMG);
    pub(crate) const CRYSTALS_GET_DAMAGED: Self = Self::from_eid(EAttrId::CRYSTALS_GET_DAMAGED);
    pub(crate) const MASS_ADDITION: Self = Self::from_eid(EAttrId::MASS_ADDITION);
    pub(crate) const AOE_VELOCITY_BONUS: Self = Self::from_eid(EAttrId::AOE_VELOCITY_BONUS);
    pub(crate) const AOE_CLOUD_SIZE_BONUS: Self = Self::from_eid(EAttrId::AOE_CLOUD_SIZE_BONUS);
    pub(crate) const SIEGE_MODE_WARP_STATUS: Self = Self::from_eid(EAttrId::SIEGE_MODE_WARP_STATUS);
    pub(crate) const DISALLOW_ASSISTANCE: Self = Self::from_eid(EAttrId::DISALLOW_ASSISTANCE);
    pub(crate) const MISSILE_ENTITY_AOE_CLOUD_SIZE_MULTIPLIER: Self =
        Self::from_eid(EAttrId::MISSILE_ENTITY_AOE_CLOUD_SIZE_MULTIPLIER);
    pub(crate) const MISSILE_ENTITY_AOE_VELOCITY_MULTIPLIER: Self =
        Self::from_eid(EAttrId::MISSILE_ENTITY_AOE_VELOCITY_MULTIPLIER);
    pub(crate) const DISALLOW_OFFENSIVE_MODIFIERS: Self = Self::from_eid(EAttrId::DISALLOW_OFFENSIVE_MODIFIERS);
    pub(crate) const SIG_RADIUS_BONUS_PERCENT: Self = Self::from_eid(EAttrId::SIG_RADIUS_BONUS_PERCENT);
    pub(crate) const HULL_EM_DMG_RESONANCE: Self = Self::from_eid(EAttrId::HULL_EM_DMG_RESONANCE);
    pub(crate) const HULL_EXPL_DMG_RESONANCE: Self = Self::from_eid(EAttrId::HULL_EXPL_DMG_RESONANCE);
    pub(crate) const HULL_KIN_DMG_RESONANCE: Self = Self::from_eid(EAttrId::HULL_KIN_DMG_RESONANCE);
    pub(crate) const HULL_THERM_DMG_RESONANCE: Self = Self::from_eid(EAttrId::HULL_THERM_DMG_RESONANCE);
    pub(crate) const MAX_GROUP_ONLINE: Self = Self::from_eid(EAttrId::MAX_GROUP_ONLINE);
    pub(crate) const SCAN_GRAVIMETRIC_STRENGTH_PERCENT: Self =
        Self::from_eid(EAttrId::SCAN_GRAVIMETRIC_STRENGTH_PERCENT);
    pub(crate) const SCAN_LADAR_STRENGTH_PERCENT: Self = Self::from_eid(EAttrId::SCAN_LADAR_STRENGTH_PERCENT);
    pub(crate) const SCAN_MAGNETOMETRIC_STRENGTH_PERCENT: Self =
        Self::from_eid(EAttrId::SCAN_MAGNETOMETRIC_STRENGTH_PERCENT);
    pub(crate) const SCAN_RADAR_STRENGTH_PERCENT: Self = Self::from_eid(EAttrId::SCAN_RADAR_STRENGTH_PERCENT);
    pub(crate) const DISALLOW_IN_EMPIRE_SPACE: Self = Self::from_eid(EAttrId::DISALLOW_IN_EMPIRE_SPACE);
    pub(crate) const IMPLANT_BONUS_VELOCITY: Self = Self::from_eid(EAttrId::IMPLANT_BONUS_VELOCITY);
    pub(crate) const BOOSTERNESS: Self = Self::from_eid(EAttrId::BOOSTERNESS);
    pub(crate) const MASS_BONUS_PERCENTAGE: Self = Self::from_eid(EAttrId::MASS_BONUS_PERCENTAGE);
    pub(crate) const UPGRADE_CAPACITY: Self = Self::from_eid(EAttrId::UPGRADE_CAPACITY);
    pub(crate) const ENTITY_MAX_VELOCITY_SIG_RADIUS_MULT: Self =
        Self::from_eid(EAttrId::ENTITY_MAX_VELOCITY_SIG_RADIUS_MULT);
    pub(crate) const UPGRADE_COST: Self = Self::from_eid(EAttrId::UPGRADE_COST);
    pub(crate) const UPGRADE_SLOTS_LEFT: Self = Self::from_eid(EAttrId::UPGRADE_SLOTS_LEFT);
    pub(crate) const SPEED_FACTOR_BONUS: Self = Self::from_eid(EAttrId::SPEED_FACTOR_BONUS);
    pub(crate) const REQUIRED_THERMODYNAMICS_SKILL: Self = Self::from_eid(EAttrId::REQUIRED_THERMODYNAMICS_SKILL);
    pub(crate) const SPEED_BOOST_FACTOR_BONUS: Self = Self::from_eid(EAttrId::SPEED_BOOST_FACTOR_BONUS);
    pub(crate) const DRONE_BANDWIDTH: Self = Self::from_eid(EAttrId::DRONE_BANDWIDTH);
    pub(crate) const DRONE_BANDWIDTH_USED: Self = Self::from_eid(EAttrId::DRONE_BANDWIDTH_USED);
    pub(crate) const CAN_FIT_SHIP_GROUP1: Self = Self::from_eid(EAttrId::CAN_FIT_SHIP_GROUP1);
    pub(crate) const CAN_FIT_SHIP_GROUP2: Self = Self::from_eid(EAttrId::CAN_FIT_SHIP_GROUP2);
    pub(crate) const CAN_FIT_SHIP_GROUP3: Self = Self::from_eid(EAttrId::CAN_FIT_SHIP_GROUP3);
    pub(crate) const CAN_FIT_SHIP_GROUP4: Self = Self::from_eid(EAttrId::CAN_FIT_SHIP_GROUP4);
    pub(crate) const CAN_FIT_SHIP_TYPE1: Self = Self::from_eid(EAttrId::CAN_FIT_SHIP_TYPE1);
    pub(crate) const CAN_FIT_SHIP_TYPE2: Self = Self::from_eid(EAttrId::CAN_FIT_SHIP_TYPE2);
    pub(crate) const CAN_FIT_SHIP_TYPE3: Self = Self::from_eid(EAttrId::CAN_FIT_SHIP_TYPE3);
    pub(crate) const CAN_FIT_SHIP_TYPE4: Self = Self::from_eid(EAttrId::CAN_FIT_SHIP_TYPE4);
    pub(crate) const MAX_RANGE_HIDDEN: Self = Self::from_eid(EAttrId::MAX_RANGE_HIDDEN);
    pub(crate) const ACTIVATION_BLOCKED: Self = Self::from_eid(EAttrId::ACTIVATION_BLOCKED);
    pub(crate) const ACTIVATION_BLOCKED_STRENGTH: Self = Self::from_eid(EAttrId::ACTIVATION_BLOCKED_STRENGTH);
    pub(crate) const AOE_DMG_REDUCTION_FACTOR: Self = Self::from_eid(EAttrId::AOE_DMG_REDUCTION_FACTOR);
    pub(crate) const SUBSYSTEM_SLOT: Self = Self::from_eid(EAttrId::SUBSYSTEM_SLOT);
    pub(crate) const MAX_SUBSYSTEMS: Self = Self::from_eid(EAttrId::MAX_SUBSYSTEMS);
    pub(crate) const TURRET_HARDPOINT_MODIFIER: Self = Self::from_eid(EAttrId::TURRET_HARDPOINT_MODIFIER);
    pub(crate) const LAUNCHER_HARDPOINT_MODIFIER: Self = Self::from_eid(EAttrId::LAUNCHER_HARDPOINT_MODIFIER);
    pub(crate) const HI_SLOT_MODIFIER: Self = Self::from_eid(EAttrId::HI_SLOT_MODIFIER);
    pub(crate) const MED_SLOT_MODIFIER: Self = Self::from_eid(EAttrId::MED_SLOT_MODIFIER);
    pub(crate) const LOW_SLOT_MODIFIER: Self = Self::from_eid(EAttrId::LOW_SLOT_MODIFIER);
    pub(crate) const FITS_TO_SHIP_TYPE: Self = Self::from_eid(EAttrId::FITS_TO_SHIP_TYPE);
    pub(crate) const MAX_GROUP_FITTED: Self = Self::from_eid(EAttrId::MAX_GROUP_FITTED);
    pub(crate) const RIG_SIZE: Self = Self::from_eid(EAttrId::RIG_SIZE);
    pub(crate) const ALLOWED_DRONE_GROUP1: Self = Self::from_eid(EAttrId::ALLOWED_DRONE_GROUP1);
    pub(crate) const ALLOWED_DRONE_GROUP2: Self = Self::from_eid(EAttrId::ALLOWED_DRONE_GROUP2);
    pub(crate) const RELOAD_TIME: Self = Self::from_eid(EAttrId::RELOAD_TIME);
    pub(crate) const DISALLOW_VS_EW_IMMUNE_TGT: Self = Self::from_eid(EAttrId::DISALLOW_VS_EW_IMMUNE_TGT);
    pub(crate) const DMG_DELAY_DURATION: Self = Self::from_eid(EAttrId::DMG_DELAY_DURATION);
    pub(crate) const RESIST_SHIFT_AMOUNT: Self = Self::from_eid(EAttrId::RESIST_SHIFT_AMOUNT);
    pub(crate) const CAN_FIT_SHIP_GROUP5: Self = Self::from_eid(EAttrId::CAN_FIT_SHIP_GROUP5);
    pub(crate) const CAN_FIT_SHIP_GROUP6: Self = Self::from_eid(EAttrId::CAN_FIT_SHIP_GROUP6);
    pub(crate) const CAN_FIT_SHIP_GROUP7: Self = Self::from_eid(EAttrId::CAN_FIT_SHIP_GROUP7);
    pub(crate) const CAN_FIT_SHIP_GROUP8: Self = Self::from_eid(EAttrId::CAN_FIT_SHIP_GROUP8);
    pub(crate) const CHARGED_ARMOR_DMG_MULT: Self = Self::from_eid(EAttrId::CHARGED_ARMOR_DMG_MULT);
    pub(crate) const CAN_FIT_SHIP_TYPE5: Self = Self::from_eid(EAttrId::CAN_FIT_SHIP_TYPE5);
    pub(crate) const NOS_OVERRIDE: Self = Self::from_eid(EAttrId::NOS_OVERRIDE);
    pub(crate) const DISALLOW_IN_HISEC: Self = Self::from_eid(EAttrId::DISALLOW_IN_HISEC);
    pub(crate) const GATE_SCRAMBLE_STATUS: Self = Self::from_eid(EAttrId::GATE_SCRAMBLE_STATUS);
    pub(crate) const GATE_SCRAMBLE_STRENGTH: Self = Self::from_eid(EAttrId::GATE_SCRAMBLE_STRENGTH);
    pub(crate) const ENERGY_WARFARE_RESIST: Self = Self::from_eid(EAttrId::ENERGY_WARFARE_RESIST);
    pub(crate) const FTR_CAPACITY: Self = Self::from_eid(EAttrId::FTR_CAPACITY);
    pub(crate) const SERVICE_SLOTS: Self = Self::from_eid(EAttrId::SERVICE_SLOTS);
    pub(crate) const CAN_FIT_SHIP_GROUP9: Self = Self::from_eid(EAttrId::CAN_FIT_SHIP_GROUP9);
    pub(crate) const LAUNCHER_GROUP4: Self = Self::from_eid(EAttrId::LAUNCHER_GROUP4);
    pub(crate) const LAUNCHER_GROUP5: Self = Self::from_eid(EAttrId::LAUNCHER_GROUP5);
    pub(crate) const LAUNCHER_GROUP6: Self = Self::from_eid(EAttrId::LAUNCHER_GROUP6);
    pub(crate) const CAN_FIT_SHIP_TYPE6: Self = Self::from_eid(EAttrId::CAN_FIT_SHIP_TYPE6);
    pub(crate) const FTR_ABIL_MISSILES_EXPLOSION_RADIUS: Self =
        Self::from_eid(EAttrId::FTR_ABIL_MISSILES_EXPLOSION_RADIUS);
    pub(crate) const FTR_ABIL_MISSILES_EXPLOSION_VELOCITY: Self =
        Self::from_eid(EAttrId::FTR_ABIL_MISSILES_EXPLOSION_VELOCITY);
    pub(crate) const REMOTE_RESIST_ID: Self = Self::from_eid(EAttrId::REMOTE_RESIST_ID);
    pub(crate) const FTR_ABIL_MISSILES_RANGE: Self = Self::from_eid(EAttrId::FTR_ABIL_MISSILES_RANGE);
    pub(crate) const FTR_SQ_SIZE: Self = Self::from_eid(EAttrId::FTR_SQ_SIZE);
    pub(crate) const FTR_ABIL_MJD_SIG_RADIUS_BONUS: Self = Self::from_eid(EAttrId::FTR_ABIL_MJD_SIG_RADIUS_BONUS);
    pub(crate) const FTR_SQ_IS_LIGHT: Self = Self::from_eid(EAttrId::FTR_SQ_IS_LIGHT);
    pub(crate) const FTR_SQ_IS_SUPPORT: Self = Self::from_eid(EAttrId::FTR_SQ_IS_SUPPORT);
    pub(crate) const FTR_SQ_IS_HEAVY: Self = Self::from_eid(EAttrId::FTR_SQ_IS_HEAVY);
    pub(crate) const FTR_SQ_MAX_SIZE: Self = Self::from_eid(EAttrId::FTR_SQ_MAX_SIZE);
    pub(crate) const FTR_TUBES: Self = Self::from_eid(EAttrId::FTR_TUBES);
    pub(crate) const FTR_LIGHT_SLOTS: Self = Self::from_eid(EAttrId::FTR_LIGHT_SLOTS);
    pub(crate) const FTR_SUPPORT_SLOTS: Self = Self::from_eid(EAttrId::FTR_SUPPORT_SLOTS);
    pub(crate) const FTR_HEAVY_SLOTS: Self = Self::from_eid(EAttrId::FTR_HEAVY_SLOTS);
    pub(crate) const FTR_ABIL_ATK_MISSILE_EXPLOSION_RADIUS: Self =
        Self::from_eid(EAttrId::FTR_ABIL_ATK_MISSILE_EXPLOSION_RADIUS);
    pub(crate) const FTR_ABIL_ATK_MISSILE_EXPLOSION_VELOCITY: Self =
        Self::from_eid(EAttrId::FTR_ABIL_ATK_MISSILE_EXPLOSION_VELOCITY);
    pub(crate) const FTR_ABIL_ATK_MISSILE_RANGE_OPTIMAL: Self =
        Self::from_eid(EAttrId::FTR_ABIL_ATK_MISSILE_RANGE_OPTIMAL);
    pub(crate) const FTR_ABIL_ATK_MISSILE_RANGE_FALLOFF: Self =
        Self::from_eid(EAttrId::FTR_ABIL_ATK_MISSILE_RANGE_FALLOFF);
    pub(crate) const DOOMSDAY_ENERGY_NEUT_RADIUS: Self = Self::from_eid(EAttrId::DOOMSDAY_ENERGY_NEUT_RADIUS);
    pub(crate) const DOOMSDAY_ENERGY_NEUT_AMOUNT: Self = Self::from_eid(EAttrId::DOOMSDAY_ENERGY_NEUT_AMOUNT);
    pub(crate) const DOOMSDAY_ENERGY_NEUT_SIG_RADIUS: Self = Self::from_eid(EAttrId::DOOMSDAY_ENERGY_NEUT_SIG_RADIUS);
    pub(crate) const DOOMSDAY_WARNING_DURATION: Self = Self::from_eid(EAttrId::DOOMSDAY_WARNING_DURATION);
    pub(crate) const DOOMSDAY_DMG_DURATION: Self = Self::from_eid(EAttrId::DOOMSDAY_DMG_DURATION);
    pub(crate) const DOOMSDAY_DMG_CYCLE_TIME: Self = Self::from_eid(EAttrId::DOOMSDAY_DMG_CYCLE_TIME);
    pub(crate) const DOOMSDAY_AOE_RANGE: Self = Self::from_eid(EAttrId::DOOMSDAY_AOE_RANGE);
    pub(crate) const DOOMSDAY_AOE_DURATION: Self = Self::from_eid(EAttrId::DOOMSDAY_AOE_DURATION);
    pub(crate) const DOOMSDAY_AOE_SIG_RADIUS: Self = Self::from_eid(EAttrId::DOOMSDAY_AOE_SIG_RADIUS);
    pub(crate) const FTR_ABIL_BOMB_TYPE: Self = Self::from_eid(EAttrId::FTR_ABIL_BOMB_TYPE);
    pub(crate) const DISALLOW_TETHERING: Self = Self::from_eid(EAttrId::DISALLOW_TETHERING);
    pub(crate) const DISALLOW_DRIVE_JUMPING: Self = Self::from_eid(EAttrId::DISALLOW_DRIVE_JUMPING);
    pub(crate) const DISALLOW_DOCKING: Self = Self::from_eid(EAttrId::DISALLOW_DOCKING);
    pub(crate) const HISEC_MODIFIER: Self = Self::from_eid(EAttrId::HISEC_MODIFIER);
    pub(crate) const LOWSEC_MODIFIER: Self = Self::from_eid(EAttrId::LOWSEC_MODIFIER);
    pub(crate) const NULLSEC_MODIFIER: Self = Self::from_eid(EAttrId::NULLSEC_MODIFIER);
    pub(crate) const SECURITY_MODIFIER: Self = Self::from_eid(EAttrId::SECURITY_MODIFIER);
    pub(crate) const CAN_FIT_SHIP_GROUP10: Self = Self::from_eid(EAttrId::CAN_FIT_SHIP_GROUP10);
    pub(crate) const FTR_REFUELING_TIME: Self = Self::from_eid(EAttrId::FTR_REFUELING_TIME);
    pub(crate) const DOOMSDAY_NO_JUMP_OR_CLOAK_DURATION: Self =
        Self::from_eid(EAttrId::DOOMSDAY_NO_JUMP_OR_CLOAK_DURATION);
    pub(crate) const DOOMSDAY_IMMOBILITY_DURATION: Self = Self::from_eid(EAttrId::DOOMSDAY_IMMOBILITY_DURATION);
    pub(crate) const MAX_TYPE_FITTED: Self = Self::from_eid(EAttrId::MAX_TYPE_FITTED);
    pub(crate) const ENERGY_NEUT_SIG_RESOLUTION: Self = Self::from_eid(EAttrId::ENERGY_NEUT_SIG_RESOLUTION);
    pub(crate) const CAN_FIT_SHIP_TYPE7: Self = Self::from_eid(EAttrId::CAN_FIT_SHIP_TYPE7);
    pub(crate) const WARFARE_BUFF1_ID: Self = Self::from_eid(EAttrId::WARFARE_BUFF1_ID);
    pub(crate) const WARFARE_BUFF1_VAL: Self = Self::from_eid(EAttrId::WARFARE_BUFF1_VAL);
    pub(crate) const WARFARE_BUFF2_ID: Self = Self::from_eid(EAttrId::WARFARE_BUFF2_ID);
    pub(crate) const WARFARE_BUFF2_VAL: Self = Self::from_eid(EAttrId::WARFARE_BUFF2_VAL);
    pub(crate) const WARFARE_BUFF3_ID: Self = Self::from_eid(EAttrId::WARFARE_BUFF3_ID);
    pub(crate) const WARFARE_BUFF3_VAL: Self = Self::from_eid(EAttrId::WARFARE_BUFF3_VAL);
    pub(crate) const CAN_FIT_SHIP_GROUP11: Self = Self::from_eid(EAttrId::CAN_FIT_SHIP_GROUP11);
    pub(crate) const CAN_FIT_SHIP_GROUP12: Self = Self::from_eid(EAttrId::CAN_FIT_SHIP_GROUP12);
    pub(crate) const CAN_FIT_SHIP_GROUP13: Self = Self::from_eid(EAttrId::CAN_FIT_SHIP_GROUP13);
    pub(crate) const CAN_FIT_SHIP_GROUP14: Self = Self::from_eid(EAttrId::CAN_FIT_SHIP_GROUP14);
    pub(crate) const CAN_FIT_SHIP_GROUP15: Self = Self::from_eid(EAttrId::CAN_FIT_SHIP_GROUP15);
    pub(crate) const CAN_FIT_SHIP_GROUP16: Self = Self::from_eid(EAttrId::CAN_FIT_SHIP_GROUP16);
    pub(crate) const CAN_FIT_SHIP_GROUP17: Self = Self::from_eid(EAttrId::CAN_FIT_SHIP_GROUP17);
    pub(crate) const CAN_FIT_SHIP_GROUP18: Self = Self::from_eid(EAttrId::CAN_FIT_SHIP_GROUP18);
    pub(crate) const CAN_FIT_SHIP_GROUP19: Self = Self::from_eid(EAttrId::CAN_FIT_SHIP_GROUP19);
    pub(crate) const CAN_FIT_SHIP_GROUP20: Self = Self::from_eid(EAttrId::CAN_FIT_SHIP_GROUP20);
    pub(crate) const CAN_FIT_SHIP_TYPE8: Self = Self::from_eid(EAttrId::CAN_FIT_SHIP_TYPE8);
    pub(crate) const CAN_FIT_SHIP_TYPE9: Self = Self::from_eid(EAttrId::CAN_FIT_SHIP_TYPE9);
    pub(crate) const CAN_FIT_SHIP_TYPE10: Self = Self::from_eid(EAttrId::CAN_FIT_SHIP_TYPE10);
    pub(crate) const BUFF_DURATION: Self = Self::from_eid(EAttrId::BUFF_DURATION);
    pub(crate) const WARFARE_BUFF4_ID: Self = Self::from_eid(EAttrId::WARFARE_BUFF4_ID);
    pub(crate) const WARFARE_BUFF4_VAL: Self = Self::from_eid(EAttrId::WARFARE_BUFF4_VAL);
    pub(crate) const ONLINE_MAX_SECURITY_CLASS: Self = Self::from_eid(EAttrId::ONLINE_MAX_SECURITY_CLASS);
    pub(crate) const DOOMSDAY_ENERGY_NEUT_RESIST_ID: Self = Self::from_eid(EAttrId::DOOMSDAY_ENERGY_NEUT_RESIST_ID);
    pub(crate) const PILOT_SECURITY_STATUS: Self = Self::from_eid(EAttrId::PILOT_SECURITY_STATUS);
    pub(crate) const MAX_FOF_TGT_RANGE: Self = Self::from_eid(EAttrId::MAX_FOF_TGT_RANGE);
    pub(crate) const DMG_MULT_BONUS_PER_CYCLE: Self = Self::from_eid(EAttrId::DMG_MULT_BONUS_PER_CYCLE);
    pub(crate) const DMG_MULT_BONUS_MAX: Self = Self::from_eid(EAttrId::DMG_MULT_BONUS_MAX);
    pub(crate) const FTR_ST_LIGHT_SLOTS: Self = Self::from_eid(EAttrId::FTR_ST_LIGHT_SLOTS);
    pub(crate) const FTR_ST_SUPPORT_SLOTS: Self = Self::from_eid(EAttrId::FTR_ST_SUPPORT_SLOTS);
    pub(crate) const FTR_ST_HEAVY_SLOTS: Self = Self::from_eid(EAttrId::FTR_ST_HEAVY_SLOTS);
    pub(crate) const FTR_SQ_IS_ST_LIGHT: Self = Self::from_eid(EAttrId::FTR_SQ_IS_ST_LIGHT);
    pub(crate) const FTR_SQ_IS_ST_SUPPORT: Self = Self::from_eid(EAttrId::FTR_SQ_IS_ST_SUPPORT);
    pub(crate) const FTR_SQ_IS_ST_HEAVY: Self = Self::from_eid(EAttrId::FTR_SQ_IS_ST_HEAVY);
    pub(crate) const CAN_FIT_SHIP_TYPE11: Self = Self::from_eid(EAttrId::CAN_FIT_SHIP_TYPE11);
    pub(crate) const REP_MULT_BONUS_PER_CYCLE: Self = Self::from_eid(EAttrId::REP_MULT_BONUS_PER_CYCLE);
    pub(crate) const REP_MULT_BONUS_MAX: Self = Self::from_eid(EAttrId::REP_MULT_BONUS_MAX);
    pub(crate) const ECM_JAM_DURATION: Self = Self::from_eid(EAttrId::ECM_JAM_DURATION);
    pub(crate) const MINING_WASTED_VOLUME_MULT: Self = Self::from_eid(EAttrId::MINING_WASTED_VOLUME_MULT);
    pub(crate) const MINING_WASTE_PROBABILITY: Self = Self::from_eid(EAttrId::MINING_WASTE_PROBABILITY);
    pub(crate) const DOOMSDAY_APPLIED_DBUFF_DURATION: Self = Self::from_eid(EAttrId::DOOMSDAY_APPLIED_DBUFF_DURATION);
    pub(crate) const DISALLOW_IN_HAZARD: Self = Self::from_eid(EAttrId::DISALLOW_IN_HAZARD);
    pub(crate) const ALLOW_IN_FULLY_CORRUPTED_LOWSEC: Self = Self::from_eid(EAttrId::ALLOW_IN_FULLY_CORRUPTED_LOWSEC);
    pub(crate) const ALLOW_IN_FULLY_CORRUPTED_HISEC: Self = Self::from_eid(EAttrId::ALLOW_IN_FULLY_CORRUPTED_HISEC);
    pub(crate) const DOT_DURATION: Self = Self::from_eid(EAttrId::DOT_DURATION);
    pub(crate) const DOT_MAX_DMG_PER_TICK: Self = Self::from_eid(EAttrId::DOT_MAX_DMG_PER_TICK);
    pub(crate) const DOT_MAX_HP_PERC_PER_TICK: Self = Self::from_eid(EAttrId::DOT_MAX_HP_PERC_PER_TICK);
    pub(crate) const VALID_TGT_WHITELIST: Self = Self::from_eid(EAttrId::VALID_TGT_WHITELIST);
    pub(crate) const MAX_DIRECTIONAL_SCAN_RANGE: Self = Self::from_eid(EAttrId::MAX_DIRECTIONAL_SCAN_RANGE);
    pub(crate) const CAN_FIT_SHIP_TYPE12: Self = Self::from_eid(EAttrId::CAN_FIT_SHIP_TYPE12);
    pub(crate) const MINING_CRIT_CHANCE: Self = Self::from_eid(EAttrId::MINING_CRIT_CHANCE);
    pub(crate) const MINING_CRIT_BONUS_YIELD: Self = Self::from_eid(EAttrId::MINING_CRIT_BONUS_YIELD);
    // Library-specific attributes
    pub(crate) const DISALLOW_WARPING_JUMPING: Self = Self::Custom(ACustomAttrId::from_i32(1));
}
