use crate::{ad::ABuffId, ec::buffs as ecb};

pub(crate) const VELOCITY_PENALTY: ABuffId = ABuffId::Eve(ecb::VELOCITY_PENALTY);
pub(crate) const WARP_PENALTY: ABuffId = ABuffId::Eve(ecb::WARP_PENALTY);
pub(crate) const DISALLOW_CLOAK: ABuffId = ABuffId::Eve(ecb::DISALLOW_CLOAK);
pub(crate) const DISALLOW_DOCK_JUMP: ABuffId = ABuffId::Eve(ecb::DISALLOW_DOCK_JUMP);
pub(crate) const PANIC_SHIELD_RESIST: ABuffId = ABuffId::Eve(ecb::PANIC_SHIELD_RESIST);
pub(crate) const PANIC_SHIELD_RECHARGE_TIME: ABuffId = ABuffId::Eve(ecb::PANIC_SHIELD_RECHARGE_TIME);
pub(crate) const STASIS_WEBIFICATION_BURST: ABuffId = ABuffId::Eve(ecb::STASIS_WEBIFICATION_BURST);
pub(crate) const WD_BURST_TURRET_MAX_RANGE: ABuffId = ABuffId::Eve(ecb::WD_BURST_TURRET_MAX_RANGE);
pub(crate) const WD_BURST_TURRET_FALLOFF_RANGE: ABuffId = ABuffId::Eve(ecb::WD_BURST_TURRET_FALLOFF_RANGE);
pub(crate) const WD_BURST_TURRET_TRACKING: ABuffId = ABuffId::Eve(ecb::WD_BURST_TURRET_TRACKING);
pub(crate) const WD_BURST_MISSILE_VELOCITY: ABuffId = ABuffId::Eve(ecb::WD_BURST_MISSILE_VELOCITY);
pub(crate) const WD_BURST_MISSILE_DURATION: ABuffId = ABuffId::Eve(ecb::WD_BURST_MISSILE_DURATION);
pub(crate) const WD_BURST_MISSILE_EXPLOSION_VELOCITY: ABuffId = ABuffId::Eve(ecb::WD_BURST_MISSILE_EXPLOSION_VELOCITY);
pub(crate) const WD_BURST_MISSILE_EXPLOSION_RADIUS: ABuffId = ABuffId::Eve(ecb::WD_BURST_MISSILE_EXPLOSION_RADIUS);
pub(crate) const DAMP_BURST_SCAN_RESOLUTION_PENALTY: ABuffId = ABuffId::Eve(ecb::DAMP_BURST_SCAN_RESOLUTION_PENALTY);
pub(crate) const DAMP_BURST_TARGETING_RANGE_PENALTY: ABuffId = ABuffId::Eve(ecb::DAMP_BURST_TARGETING_RANGE_PENALTY);
pub(crate) const SIGNATURE_RADIUS_PENALTY: ABuffId = ABuffId::Eve(ecb::SIGNATURE_RADIUS_PENALTY);
pub(crate) const PANIC_SCAN_RESOLUTION_PENALTY: ABuffId = ABuffId::Eve(ecb::PANIC_SCAN_RESOLUTION_PENALTY);
pub(crate) const PANIC_MASS_INCREASE: ABuffId = ABuffId::Eve(ecb::PANIC_MASS_INCREASE);
pub(crate) const DISALLOW_TETHER: ABuffId = ABuffId::Eve(ecb::DISALLOW_TETHER);
pub(crate) const PANIC_DRONE_DMG_PENALTY: ABuffId = ABuffId::Eve(ecb::PANIC_DRONE_DMG_PENALTY);
pub(crate) const PANIC_DISALLOW_WEAPONS: ABuffId = ABuffId::Eve(ecb::PANIC_DISALLOW_WEAPONS);
pub(crate) const PANIC_DISALLOW_ENTOSIS: ABuffId = ABuffId::Eve(ecb::PANIC_DISALLOW_ENTOSIS);
pub(crate) const REMOTE_REPAIR_IMPEDANCE: ABuffId = ABuffId::Eve(ecb::REMOTE_REPAIR_IMPEDANCE);
pub(crate) const SOV_SMOD_SHIELD_HITPOINT_BONUS: ABuffId = ABuffId::Eve(ecb::SOV_SMOD_SHIELD_HITPOINT_BONUS);
pub(crate) const SOV_SMOD_CAPACITOR_CAPACITY_BONUS: ABuffId = ABuffId::Eve(ecb::SOV_SMOD_CAPACITOR_CAPACITY_BONUS);
pub(crate) const SOV_SMOD_ARMOR_HITPOINT_BONUS: ABuffId = ABuffId::Eve(ecb::SOV_SMOD_ARMOR_HITPOINT_BONUS);
pub(crate) const SOV_SMOD_MODULE_OVERHEAT_BONUS: ABuffId = ABuffId::Eve(ecb::SOV_SMOD_MODULE_OVERHEAT_BONUS);
pub(crate) const SOV_SMOD_CAPACITOR_RECHARGE_BONUS: ABuffId = ABuffId::Eve(ecb::SOV_SMOD_CAPACITOR_RECHARGE_BONUS);
pub(crate) const SOV_SMOD_TARGETING_AND_DSCAN_RANGE_BONUS: ABuffId =
    ABuffId::Eve(ecb::SOV_SMOD_TARGETING_AND_DSCAN_RANGE_BONUS);
pub(crate) const SOV_SMOD_SCAN_RESOLUTION_BONUS: ABuffId = ABuffId::Eve(ecb::SOV_SMOD_SCAN_RESOLUTION_BONUS);
pub(crate) const SOV_SMOD_WARP_SPEED_ADD: ABuffId = ABuffId::Eve(ecb::SOV_SMOD_WARP_SPEED_ADD);
pub(crate) const SOV_SMOD_SHIELD_BOOSTER_BONUS: ABuffId = ABuffId::Eve(ecb::SOV_SMOD_SHIELD_BOOSTER_BONUS);
pub(crate) const SOV_SMOD_ARMOR_REPAIRER_BONUS: ABuffId = ABuffId::Eve(ecb::SOV_SMOD_ARMOR_REPAIRER_BONUS);

// Library-specific buffs
pub(crate) const DISALLOW_WARP_JUMP_DRIVE: ABuffId = ABuffId::Custom(1);
