use crate::{ad::AItemId, ed::EItemId};

impl AItemId {
    pub(crate) const MISSILE_LAUNCHER_OPERATION: Self = Self::from_eid(EItemId::MISSILE_LAUNCHER_OPERATION);
    pub(crate) const GUNNERY: Self = Self::from_eid(EItemId::GUNNERY);
    pub(crate) const HIGH_SPEED_MANEUVERING: Self = Self::from_eid(EItemId::HIGH_SPEED_MANEUVERING);
    pub(crate) const MICRO_JUMP_DRIVE_OPERATION: Self = Self::from_eid(EItemId::MICRO_JUMP_DRIVE_OPERATION);
    pub(crate) const ICE_HARVESTING: Self = Self::from_eid(EItemId::ICE_HARVESTING);
    pub(crate) const CAPITAL_SHIPS: Self = Self::from_eid(EItemId::CAPITAL_SHIPS);
    pub(crate) const WARP_DISRUPT_PROBE: Self = Self::from_eid(EItemId::WARP_DISRUPT_PROBE);
    pub(crate) const THERMODYNAMICS: Self = Self::from_eid(EItemId::THERMODYNAMICS);
    pub(crate) const NANITE_REPAIR_PASTE: Self = Self::from_eid(EItemId::NANITE_REPAIR_PASTE);
    pub(crate) const VENTURE: Self = Self::from_eid(EItemId::VENTURE);
    pub(crate) const SURGICAL_WARP_DISRUPT_PROBE: Self = Self::from_eid(EItemId::SURGICAL_WARP_DISRUPT_PROBE);
    pub(crate) const CONFESSOR: Self = Self::from_eid(EItemId::CONFESSOR);
    pub(crate) const CONFESSOR_DEFENSE_MODE: Self = Self::from_eid(EItemId::CONFESSOR_DEFENSE_MODE);
    pub(crate) const CONFESSOR_SHARPSHOOTER_MODE: Self = Self::from_eid(EItemId::CONFESSOR_SHARPSHOOTER_MODE);
    pub(crate) const CONFESSOR_PROPULSION_MODE: Self = Self::from_eid(EItemId::CONFESSOR_PROPULSION_MODE);
    pub(crate) const SVIPUL: Self = Self::from_eid(EItemId::SVIPUL);
    pub(crate) const SVIPUL_DEFENSE_MODE: Self = Self::from_eid(EItemId::SVIPUL_DEFENSE_MODE);
    pub(crate) const SVIPUL_PROPULSION_MODE: Self = Self::from_eid(EItemId::SVIPUL_PROPULSION_MODE);
    pub(crate) const SVIPUL_SHARPSHOOTER_MODE: Self = Self::from_eid(EItemId::SVIPUL_SHARPSHOOTER_MODE);
    pub(crate) const JACKDAW: Self = Self::from_eid(EItemId::JACKDAW);
    pub(crate) const JACKDAW_DEFENSE_MODE: Self = Self::from_eid(EItemId::JACKDAW_DEFENSE_MODE);
    pub(crate) const JACKDAW_PROPULSION_MODE: Self = Self::from_eid(EItemId::JACKDAW_PROPULSION_MODE);
    pub(crate) const JACKDAW_SHARPSHOOTER_MODE: Self = Self::from_eid(EItemId::JACKDAW_SHARPSHOOTER_MODE);
    pub(crate) const HECATE: Self = Self::from_eid(EItemId::HECATE);
    pub(crate) const HECATE_DEFENSE_MODE: Self = Self::from_eid(EItemId::HECATE_DEFENSE_MODE);
    pub(crate) const HECATE_PROPULSION_MODE: Self = Self::from_eid(EItemId::HECATE_PROPULSION_MODE);
    pub(crate) const HECATE_SHARPSHOOTER_MODE: Self = Self::from_eid(EItemId::HECATE_SHARPSHOOTER_MODE);
    pub(crate) const STASIS_WEBIFICATION_PROBE: Self = Self::from_eid(EItemId::STASIS_WEBIFICATION_PROBE);
    pub(crate) const CAPITAL_MICRO_JUMP_DRIVE_OPERATION: Self =
        Self::from_eid(EItemId::CAPITAL_MICRO_JUMP_DRIVE_OPERATION);
    pub(crate) const GAMMA_STABILITY_GENERATOR: Self = Self::from_eid(EItemId::GAMMA_STABILITY_GENERATOR);
    pub(crate) const PLASMA_STABILITY_GENERATOR: Self = Self::from_eid(EItemId::PLASMA_STABILITY_GENERATOR);
    pub(crate) const ELECTRIC_STABILITY_GENERATOR: Self = Self::from_eid(EItemId::ELECTRIC_STABILITY_GENERATOR);
    pub(crate) const EXOTIC_STABILITY_GENERATOR: Self = Self::from_eid(EItemId::EXOTIC_STABILITY_GENERATOR);
    pub(crate) const PIONEER: Self = Self::from_eid(EItemId::PIONEER);
    pub(crate) const PIONEER_CONSORTIUM_ISSUE: Self = Self::from_eid(EItemId::PIONEER_CONSORTIUM_ISSUE);
    pub(crate) const VENTURE_CONSORTIUM_ISSUE: Self = Self::from_eid(EItemId::VENTURE_CONSORTIUM_ISSUE);
    pub(crate) const OUTRIDER: Self = Self::from_eid(EItemId::OUTRIDER);
    pub(crate) const ANHINGA: Self = Self::from_eid(EItemId::ANHINGA);
    pub(crate) const SKUA: Self = Self::from_eid(EItemId::SKUA);
    pub(crate) const SKUA_DEFENSE_MODE: Self = Self::from_eid(EItemId::SKUA_DEFENSE_MODE);
    pub(crate) const ANHINGA_PRIMARY_MODE: Self = Self::from_eid(EItemId::ANHINGA_PRIMARY_MODE);
    pub(crate) const SKUA_PROPULSION_MODE: Self = Self::from_eid(EItemId::SKUA_PROPULSION_MODE);
    pub(crate) const ANHINGA_SECONDARY_MODE: Self = Self::from_eid(EItemId::ANHINGA_SECONDARY_MODE);
    pub(crate) const SKUA_SHARPSHOOTER_MODE: Self = Self::from_eid(EItemId::SKUA_SHARPSHOOTER_MODE);
    pub(crate) const ANHINGA_TERTIARY_MODE: Self = Self::from_eid(EItemId::ANHINGA_TERTIARY_MODE);
}
