pub use sole_add_fighter::AddFighterError;
pub use sole_add_fighter_proj::AddFighterProjError;
pub use sole_change_fighter_proj::ChangeFighterProjError;
pub use sole_get_fighter::GetFighterInfoError;
pub use sole_get_fit_fighters::GetFitFighterInfosError;
pub use sole_remove_fighter::RemoveFighterError;
pub use sole_remove_fighter_count_override::RemoveFighterCountOverrideError;
pub use sole_remove_fighter_proj::RemoveFighterProjError;
pub use sole_set_fighter_count_override::SetFighterCountOverrideError;
pub use sole_set_fighter_state::SetFighterStateError;

mod sole_add_fighter;
mod sole_add_fighter_proj;
mod sole_change_fighter_proj;
mod sole_get_fighter;
mod sole_get_fit_fighters;
mod sole_remove_fighter;
mod sole_remove_fighter_count_override;
mod sole_remove_fighter_proj;
mod sole_set_fighter_count_override;
mod sole_set_fighter_state;
