//! Solar system item definitions.

pub(in crate::sol) use base::{ItemMutationData, get_combined_a_attr_values};
use base::{UadItemBase, UadItemBaseMutable};
pub(in crate::sol) use container::Items;
pub(crate) use item::UadItem;
pub(in crate::sol) use item_autocharge::UadAutocharge;
pub(in crate::sol) use item_booster::UadBooster;
pub(in crate::sol) use item_character::UadCharacter;
pub(in crate::sol) use item_charge::UadCharge;
pub(in crate::sol) use item_drone::UadDrone;
pub(in crate::sol) use item_fighter::UadFighter;
pub(in crate::sol) use item_fw_effect::UadFwEffect;
pub(in crate::sol) use item_implant::UadImplant;
pub(in crate::sol) use item_module::UadModule;
pub(in crate::sol) use item_proj_effect::UadProjEffect;
pub(in crate::sol) use item_rig::UadRig;
pub(in crate::sol) use item_service::UadService;
pub(in crate::sol) use item_ship::{ShipKind, UadShip};
pub(in crate::sol) use item_skill::UadSkill;
pub(in crate::sol) use item_stance::UadStance;
pub(in crate::sol) use item_subsystem::UadSubsystem;
pub(in crate::sol) use item_sw_effect::UadSwEffect;
use misc::{Autocharges, EffectModes, Projs, bool_to_state_active, bool_to_state_offline, state_to_bool};

mod base;
mod container;
mod item;
mod item_autocharge;
mod item_booster;
mod item_character;
mod item_charge;
mod item_drone;
mod item_fighter;
mod item_fw_effect;
mod item_implant;
mod item_module;
mod item_proj_effect;
mod item_rig;
mod item_service;
mod item_ship;
mod item_skill;
mod item_stance;
mod item_subsystem;
mod item_sw_effect;
mod misc;
